language: rust

git:
  depth: false

dist: trusty
sudo: required

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

matrix:
  include:
#    - os: linux
#      env: TEST_SUITE=servers
#    - os: linux
#      env: TEST_SUITE=chain-core
#    - os: linux
#      env: TEST_SUITE=pool-p2p-src
#    - os: linux
#      env: TEST_SUITE=keychain
#    - os: linux
#      env: TEST_SUITE=api-util-store
#    - os: osx
#      env: TEST_SUITE=release
    - os: windows
      env: TEST_SUITE=release

script:
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[0]};
    echo "start testing on folder $DIR...";
    if [[ -n "$DIR" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]];  then cd $DIR && cargo test --release && cd - > /dev/null; fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[1]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[2]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;

before_deploy:
  - if [[ "$TEST_SUITE" == "pool-p2p-src" ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: VaCOjEWoaru4VaM9+pQnAx5m5eN8es0iV2JiVx55egD7hpP/ODL6rg4PPJLbop05Z2lPpWkKb7mZ3oZzNv9WcViJufQkEDGpzsazp6abjbrvwdwoxPZHP5iUCOjj7oCQS2VTr9t0fOfqEcsbOfk7s2RN24bZJp8z2uOw5QKaW8YrH83Ez8siCdmYhHtOQSpSHZKCfU9j5oo8iSpSDRpiw2pmC7GnqrUSUkosI4TwzhDLMYkzL+WLTSy2k4P+/463OubG8czhe/H4E6lXOTeOQoJu54eU+2A+9FJi7cG4bVb3l2/LOahhBE2dxencCkmIv85z+nHgWgxsnTFQgy+SGtkvJ+TGEzdzSYwL/atxT8yTxHTHqqYbFSCqoue8wF8+bEwkFq+mX8e9lVCmyjO23hOzyaltw7oe9dyKxOOEZfmLqyAHeohPVzn0/pMQ//S60FNMlPGYPbK/J6wFOwWu2tzLfzrXb1zfxG2wbQPIMBYuFbo38XEbI8NjvHoCN+FmKBW8z8yu0jpR2cKiVS2Jmy7sZqfddhR46VxL+cQauvi2KflecKUZvbY+aKadDcN8AZFCb+KWt3vGUArrSV5JU4FagtEGPPNu0RPsAr+SIoOgLt16B61wHhcf5LnaRPRGFCSyhZwwWkGTzZVx3OPbB+FcBfFWRMMw5RmtNYrbYbc=
  file_glob: true
  file: target/release/grin-*.*
  skip_cleanup: true
  on:
    repo: yeastplume/grin
    tags: true
